name: Build and Push Image

on:
  workflow_run:
    workflows: ["Deploy resource_group, acr,acr_secret,key_vault"]
    types:
      - completed

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Download All Artifacts from Last Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Find the latest successful run of Create-3-resource.yml
          RUN_ID=$(gh run list --workflow Create-3-resource.yml --status completed --json databaseId --jq ".[0].databaseId")

          if [[ -z "$RUN_ID" ]]; then
            echo "❌ No previous workflow run found!"
            exit 1
          fi

          echo "Downloading ALL artifacts from run ID: $RUN_ID"
          gh run download $RUN_ID --dir ./downloaded-artifacts

          echo "✅ All artifacts downloaded successfully!"

      - name: Extract ACR Name
        run: |
          acr_name=$(terraform output -raw acr_name 2>/dev/null || echo "")
          if [[ -z "$acr_name" ]]; then
            echo "❌ Failed to retrieve acr_name from Terraform output."
            exit 1
          fi
          echo "✅ acr name: $acr_name"
          echo "acr_name=$acr_name" >> $GITHUB_ENV


      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          
      
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        env:
          ARM_USE_OIDC: true
        run: terraform init -backend-config="envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend"



      - name: Authenticate to ACR
        run: az acr login --name $acr_name

      - name: Build and Push Docker Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/myapp:latest .
          docker push $ACR_NAME.azurecr.io/myapp:latest
