name: Destroy ACI

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (dev, uat, prod)'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan

      - name: Set ENV Based on Input
        run: |
          echo "ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV

      - name: Log in to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          if [ ! -f envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend ]; then
            echo "Backend file not found!"
            exit 1
          fi
          terraform init -backend-config=envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend

      - name: Terraform Destroy
        run: |
          terraform destroy -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" -auto-approve
