name: Destroy ACI Resources

on:
  workflow_dispatch: # This allows manual triggering of the workflow

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Set ENV Based on Input
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "ENV=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          fi

      - name: Log in to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          if [ ! -f envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend ]; then
            echo "Backend file not found!"
            exit 1
          fi
          terraform init -backend-config=envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend

      - name: Destroy ACI Resources
        run: |
          terraform destroy -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" -auto-approve