name: Destroy Terraform Resources

on:
  workflow_dispatch:  # Allows manual execution from GitHub Actions UI

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  destroy-terraform-resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set ENV Based on Branch
        run: |
          BRANCH=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
          echo "ENV=$BRANCH" >> $GITHUB_ENV

      - name: Log in to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (for Destroy)
        env:
          ARM_USE_OIDC: true
        run: |
          BACKEND_FILE="envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend"
          terraform init -backend-config="$BACKEND_FILE"

      - name: Terraform Destroy
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform destroy -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" \
            -var="image_tag=${{ github.sha }}" \
            -auto-approve 2>&1 | tee terraform_destroy.log || echo "Terraform Destroy failed, but continuing..."

      - name: Upload Destroy Log
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-log
          path: terraform_destroy.log
          retention-days: 5