name: Deploy to ACI

on:
  workflow_run:
    workflows: ["Build and Push ACR"]
    types:
      - completed  # Only runs after build is completed
    conclusion: success  # Runs only if build succeeds

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - List Terraform Files
        run: ls -R

      - name: Log in to Azure with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (Plan Only - Debugging)
        run: terraform plan -var="environment=dev" -out=tfplan

      - name: Extract ACR & ACI Names from Terraform
        run: |
          ACR_NAME=$(terraform output -raw acr_name)
          ACI_NAME=$(terraform output -raw aci_name)
          echo "Extracted ACR Name: $ACR_NAME"
          echo "Extracted ACI Name: $ACI_NAME"
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV
          echo "ACI_NAME=$ACI_NAME" >> $GITHUB_ENV

      - name: Debug - Get ACR Login Server
        run: |
          ACR_LOGIN=$(az acr show --name $ACR_NAME --query loginServer --output tsv)
          echo "ACR Login Server: $ACR_LOGIN"
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN" >> $GITHUB_ENV

      - name: Debug - Check ACR Credentials in Key Vault
        run: |
          echo "Retrieving ACR credentials from Key Vault..."
          az keyvault secret show --name "${{ env.ACR_NAME }}-acr-username" --vault-name my-keyvault
          az keyvault secret show --name "${{ env.ACR_NAME }}-acr-password" --vault-name my-keyvault

      - name: Terraform Apply
        run: |
          echo "Deploying ACI..."
          terraform apply -var="environment=dev" -auto-approve