name: Build and Push to ACR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug - List Terraform Files
        run: ls -R

      - name: Log in to Azure with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (Plan Only - Debugging)
        run: terraform plan -var="environment=dev" -out=tfplan

      - name: Extract ACR Name from Terraform
        run: |
          ACR_NAME=$(terraform output -raw acr_name)
          echo "Extracted ACR Name: $ACR_NAME"
          echo "ACR_NAME=$ACR_NAME" >> $GITHUB_ENV

      - name: Get ACR Login Server
        run: |
          ACR_LOGIN=$(az acr show --name $ACR_NAME --query loginServer --output tsv)
          echo "ACR Login Server: $ACR_LOGIN"
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN" >> $GITHUB_ENV

      - name: Debug - Check ACR Credentials in Key Vault
        run: |
          echo "Retrieving ACR credentials from Key Vault..."
          az keyvault secret show --name "${{ env.ACR_NAME }}-acr-username" --vault-name my-keyvault
          az keyvault secret show --name "${{ env.ACR_NAME }}-acr-password" --vault-name my-keyvault

      - name: Build and Tag Image
        run: |
          echo "Building Docker image..."
          docker build -t $ACR_LOGIN_SERVER/flask-app:${{ github.sha }} -f app/Dockerfile .

      - name: Push Image to ACR
        run: |
          echo "Logging into ACR..."
          az acr login --name $ACR_NAME
          echo "Pushing Docker image..."
          docker push $ACR_LOGIN_SERVER/flask-app:${{ github.sha }}

      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: app/Dockerfile
