name: Deploy Terraform

on:
  workflow_run:
    workflows: ["Validate and Plan Terraform"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Branch Name
        run: |
          BRANCH_NAME="${{ github.event.workflow_run.head_branch }}"
          echo "Branch detected: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Set Environment Variables
        run: |
          case "$BRANCH_NAME" in
            dev) echo "ENV=dev" >> $GITHUB_ENV ;;
            uat) echo "ENV=uat" >> $GITHUB_ENV ;;
            prod) echo "ENV=prod" >> $GITHUB_ENV ;;
            *) echo "❌ Unknown branch: $BRANCH_NAME. Exiting..."; exit 1 ;;
          esac

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verify Terraform Version
        run: terraform version

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Check Backend and tfvars Files
        run: |
          BACKEND_FILE="envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend"
          TFVARS_FILE="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars"

          if [[ ! -f "$BACKEND_FILE" ]]; then
            echo "❌ Backend config file not found: $BACKEND_FILE"
            exit 1
          fi

          if [[ ! -f "$TFVARS_FILE" ]]; then
            echo "❌ tfvars file not found: $TFVARS_FILE"
            exit 1
          fi

          echo "✅ All required files exist."

      - name: Terraform Init
        env:
          ARM_USE_OIDC: true
        run: terraform init -backend-config="envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend"

      - name: Apply Terraform Plan
        env:
          ARM_USE_OIDC: true
        run: terraform apply -auto-approve -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" tfplan