name: Release to ACI

on:
  workflow_run:
    workflows: ["Validate and Plan Terraform"]
    types:
      - completed
    branches:
      - dev
      - uat
      - prod

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' # Run only if build.yml was successful

    steps:
      - name: Extract Environment Based on Branch
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${{ github.event.workflow_run.head_branch }}" == "uat" ]]; then
            echo "ENV=uat" >> $GITHUB_ENV
          elif [[ "${{ github.event.workflow_run.head_branch }}" == "prod" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Log in to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          BACKEND_FILE="envs/${{ env.ENV }}/backend-${{ env.ENV }}.tfbackend"
          if [ ! -f "$BACKEND_FILE" ]; then
            echo "Backend file not found!"
            exit 1
          fi
          terraform init -backend-config="$BACKEND_FILE"

      - name: Deploy to Azure Container Instance
        run: |
          terraform apply -var-file="envs/${{ env.ENV }}/${{ env.ENV }}.tfvars" -auto-approve